SAVE_EMAIL_USER_TOKEN_EXPIRES = 24 * 60 * 60  # token的有效期

USER_ADDRESS_COUNTS_LIMIT = 20  # 每个用户拥有最大地址数据

# 图片验证码Redis有效期， 单位：秒
IMAGE_CODE_REDIS_EXPIRES = 300

SAVE_QQ_USER_TOKEN_EXPIRES = 300  # token的有效期
